name = "readest-personal"
main = ".open-next/worker.js"
compatibility_date = "2026-04-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = true
preview_urls = true

[vars]
PNPM_VERSION = "10.28.1"

[observability]
enabled = true
head_sampling_rate = 0.01
logs = { head_sampling_rate = 0.01 }
traces = { head_sampling_rate = 0.01 }

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[kv_namespaces]]
binding = "TRANSLATIONS_KV"
id = "2222cc1c022b4fce941b1473d21e705f"

[[kv_namespaces]]
binding = "NEXT_INC_CACHE_KV"
id = "76a5842255234d9f89cd0034feb4a63d"

